fixtures:
  symlinks:
    nss_pam_ldapd: "#{source_dir}"
  repositories:
    # Compat for Puppet < 3.0
    # (installing the gem does not seem to suffice)
    'hiera-puppet':
      repo: 'https://github.com/puppetlabs/hiera-puppet.git'
      ref: '1.0.0'
